server:
  port: 2333

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.84.60:3306/hxfont?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    #    url: jdbc:mysql://127.0.0.1:3306/survey?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    #    url: jdbc:mysql://121.4.194.98:3306/survey?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: hxfont
    password: root

mybatis-plus:
  type-aliases-package: com.huaxin.api.mapper
  mapper-locations: classpath:/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
